title: 苏大晟
profile_img: /assets/img/avator.png
icon_img: /assets/img/icon.jpg

name: "苏大晟"
job: "Java 研发⼯程师"

baseurl: /resume/

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
